version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  users:
    image: golang:1.19-bullseye
    container_name: users
    working_dir: /src
    command: go run main.go
    volumes:
      - ./src/users:/src
      - ./src/pkg:/src/pkg
    links: 
        - rabbitmq
    restart: always

  credit-cards:
    image: golang:1.19-bullseye
    container_name: credit-cards
    working_dir: /src
    command: go run main.go
    volumes:
      - ./src/credit-cards:/src
      - ./src/pkg:/src/pkg
    links: 
        - rabbitmq
    restart: always

  processor:
    image: golang:1.19-bullseye
    container_name: processor
    working_dir: /src
    command: go run main.go
    volumes:
      - ./src/processor:/src
      - ./src/users/internal/user:/src/internal/user
      - ./src/credit-cards/internal/ccard:/src/internal/ccard
      - ./src/pkg:/src/pkg
    links: 
        - rabbitmq
    restart: always

